
sudo: required
dist: trusty
language: node_js

node_js:
  - "7.8.0"

before_script:
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - mkdir $HOME/bin
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
install:
  - npm install
  - ipfs init
  - ipfs daemon &
script:
  - npm run test